### ISSUE TITLE
Update capistrano scripts per new best practices

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/bassi_veratti#11]
se: https://github.com/sul-dlss/DeveloperPlaybook/blob/master/best-practices/deployment.md

**Comment by atz** [comment]
Already using `OneTimeKey`.  Updated to using `dlss-capistrano` in #19.  Need advice on audit and `releaseboard`.

**Comment by atz** [comment]
Chris says audit should be set and `releaseboard` is unnecessary after honeybadger is integrated.  @eefahy anything else?

**Comment by atz** [comment]
@eefahy anything else?

**Comment by atz** [comment]
Closing this.  Reopen if needed.
