### ISSUE TITLE
Review travis build ruby versions

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/bassi_veratti#21]
Currently, we have builds against ruby versions 1.9.3, 2.1, and 2.2.4. The bassi machines all have ruby version 2.2.4. Can we drop the builds for 1.9.3 and 2.1? Should we keep one or both of the older builds?

**Comment by cbeer** [comment]
Drop away. No sense testing versions we have no intention of ever running.

**Comment by atz** [comment]
Done in #23
